- name: init master config
  template: src=kubeadm.conf dest=/home/kubeadm.conf

- name: init master insecure config
  template: src=kubeadm.conf_insecure dest=/home/kubeadm.conf
  when: INSECURE_REGISTRY_ENABLE

- name: reset master
  shell: kubeadm reset

- name: install master
  shell: kubeadm init --config /home/kubeadm.conf

- name: create ~/.kube dir
  file: path=~/.kube state=directory

- name: configure kubectl config
  shell: cp /etc/kubernetes/admin.conf ~/.kube/config

- name: fetch admin.conf
  fetch: src=/etc/kubernetes/admin.conf dest={{ADMIN_CONF}} flat=yes

- name: init flannel conf
  template: src=kube-flannel.yaml dest=/etc/kubernetes/kube-flannel.yaml

- name: init flannel conf
  template: src=kube-flannel.yaml_insecure dest=/etc/kubernetes/kube-flannel.yaml
  when: INSECURE_REGISTRY_ENABLE

- name: create flannel network
  shell: kubectl create -f /etc/kubernetes/kube-flannel.yaml
